name: Sync Supabase → Notion

on:
  schedule:
    - cron: "0 15 * * *"   # 11:00 in New York during EDT (UTC-4)
    - cron: "0 16 * * *"   # 11:00 in New York during EST (UTC-5)
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.3'
          use-public-rspm: true

      - name: Install system libraries (for RPostgres/curl)
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev libcurl4-openssl-dev libssl-dev

      # Get current hour in New York and expose it as an output
      - id: nytime
        name: Get New York hour
        run: echo "hour=$(TZ=America/New_York date +%H)" >> $GITHUB_OUTPUT

      - name: Run Notion sync
        if: ${{ github.event_name != 'schedule' || steps.nytime.outputs.hour == '11' }}
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          SUPABASE_HOST: ${{ secrets.SUPABASE_HOST }}
          SUPABASE_USER: ${{ secrets.SUPABASE_USER }}
          SUPABASE_PWD:  ${{ secrets.SUPABASE_PWD }}
          SUPABASE_DB:   ${{ secrets.SUPABASE_DB }}
          SUPABASE_PORT: ${{ secrets.SUPABASE_PORT }}
          LOOKBACK_HOURS: "17532"
        run: Rscript sync_notion.R
